/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author julia
 */
public class Vista extends javax.swing.JFrame {

    /**
     * Creates new form Vista
     */
    public Vista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TabbClientes = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        lblIdentificacion = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblApellido = new javax.swing.JLabel();
        lblDireccion = new javax.swing.JLabel();
        lblCorrero = new javax.swing.JLabel();
        lblCiudad = new javax.swing.JLabel();
        txtidentificacion = new javax.swing.JTextField();
        txtnombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        txtCiudad = new javax.swing.JTextField();
        botonEliminar = new javax.swing.JButton();
        botonInsetar = new javax.swing.JButton();
        botonModificar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lblNumerofactura = new javax.swing.JLabel();
        lblfacturaIdentificacion = new javax.swing.JLabel();
        lblfacturafecha = new javax.swing.JLabel();
        txtfacturanumerofactura = new javax.swing.JTextField();
        txtfacturaidentificacion = new javax.swing.JTextField();
        txtfacturafecha = new javax.swing.JTextField();
        botonfacturaInsertar = new javax.swing.JButton();
        botonfacturamodificar = new javax.swing.JButton();
        botonfacturaeliminar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtAcodigo = new javax.swing.JTextField();
        txtAdescripcion = new javax.swing.JTextField();
        txtApreciounitario = new javax.swing.JTextField();
        txtAunidaddemedida = new javax.swing.JTextField();
        txtApreveedor = new javax.swing.JTextField();
        txtAciudad = new javax.swing.JTextField();
        botonarticulosInsertar = new javax.swing.JButton();
        botonarticulosmodificar = new javax.swing.JButton();
        botoneliminararticulos = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtdetalleNumeroFactura = new javax.swing.JTextField();
        txtdetalleCodigo = new javax.swing.JTextField();
        txtdetalleCantidad = new javax.swing.JTextField();
        txtdetalleValorUnitario = new javax.swing.JTextField();
        txtdetalleValorTotal = new javax.swing.JTextField();
        botondetalleinsertar = new javax.swing.JButton();
        botondetallemodificar = new javax.swing.JButton();
        botondetalleEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TabbClientes.setBackground(new java.awt.Color(143, 209, 223));
        TabbClientes.setBorder(new javax.swing.border.MatteBorder(null));

        jPanel1.setBackground(new java.awt.Color(206, 219, 227));

        lblIdentificacion.setText("Identificacion");

        lblNombre.setText("Nombre");

        lblApellido.setText("Apellido");

        lblDireccion.setText("DireccionResidencia ");

        lblCorrero.setText("Correoelectronico ");

        lblCiudad.setText("Ciudad ");

        txtnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombreActionPerformed(evt);
            }
        });

        txtCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoActionPerformed(evt);
            }
        });

        botonEliminar.setText("Eliminar");
        botonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarActionPerformed(evt);
            }
        });

        botonInsetar.setText("insertar");
        botonInsetar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonInsetarActionPerformed(evt);
            }
        });

        botonModificar.setText("Modificar");
        botonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonModificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDireccion)
                            .addComponent(lblCorrero, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCiudad))
                        .addGap(198, 198, 198)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtidentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(botonEliminar)
                        .addGap(18, 18, 18)
                        .addComponent(botonInsetar)
                        .addGap(18, 18, 18)
                        .addComponent(botonModificar)))
                .addContainerGap(101, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdentificacion)
                    .addComponent(txtidentificacion))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(txtnombre))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblApellido)
                    .addComponent(txtApellido))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDireccion)
                    .addComponent(txtDireccion))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCorreo)
                    .addComponent(lblCorrero))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblCiudad)
                    .addComponent(txtCiudad))
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonEliminar)
                    .addComponent(botonInsetar)
                    .addComponent(botonModificar))
                .addGap(227, 227, 227))
        );

        TabbClientes.addTab("clientes", jPanel1);

        jPanel3.setBackground(new java.awt.Color(206, 219, 227));

        lblNumerofactura.setText("Numerofactura");

        lblfacturaIdentificacion.setText("Identificacion");

        lblfacturafecha.setText("Fecha");

        botonfacturaInsertar.setText("Insertar");
        botonfacturaInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonfacturaInsertarActionPerformed(evt);
            }
        });

        botonfacturamodificar.setText("Modificar");
        botonfacturamodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonfacturamodificarActionPerformed(evt);
            }
        });

        botonfacturaeliminar.setText("Eliminar");
        botonfacturaeliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonfacturaeliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNumerofactura)
                            .addComponent(lblfacturaIdentificacion)
                            .addComponent(lblfacturafecha))
                        .addGap(198, 198, 198)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtfacturanumerofactura, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                            .addComponent(txtfacturaidentificacion)
                            .addComponent(txtfacturafecha)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(botonfacturaInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botonfacturamodificar)
                        .addGap(18, 18, 18)
                        .addComponent(botonfacturaeliminar)))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumerofactura)
                    .addComponent(txtfacturanumerofactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfacturaidentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblfacturaIdentificacion))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfacturafecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblfacturafecha))
                .addGap(53, 53, 53)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonfacturaInsertar)
                    .addComponent(botonfacturamodificar)
                    .addComponent(botonfacturaeliminar))
                .addContainerGap(212, Short.MAX_VALUE))
        );

        TabbClientes.addTab("factura", jPanel3);

        jPanel2.setBackground(new java.awt.Color(206, 219, 227));

        jLabel1.setText("Codigo");

        jLabel2.setText("Descripción");

        jLabel3.setText("PrecioUnitario");

        jLabel4.setText("Unidadmedida");

        jLabel5.setText("Proveedor");

        jLabel6.setText("Ciudad");

        txtAcodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAcodigoActionPerformed(evt);
            }
        });

        txtAciudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAciudadActionPerformed(evt);
            }
        });

        botonarticulosInsertar.setText("Insertar");
        botonarticulosInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonarticulosInsertarActionPerformed(evt);
            }
        });

        botonarticulosmodificar.setText("Modificar");

        botoneliminararticulos.setText("Eliminar");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(198, 198, 198)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAdescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtApreciounitario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAunidaddemedida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtApreveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAciudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(botonarticulosInsertar)
                        .addGap(18, 18, 18)
                        .addComponent(botonarticulosmodificar)
                        .addGap(18, 18, 18)
                        .addComponent(botoneliminararticulos)))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtAciudad, txtAcodigo, txtAdescripcion, txtApreciounitario, txtApreveedor, txtAunidaddemedida});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtAcodigo))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtAdescripcion))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtApreciounitario))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtAunidaddemedida))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtApreveedor))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtAciudad))
                .addGap(53, 53, 53)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonarticulosInsertar)
                    .addComponent(botonarticulosmodificar)
                    .addComponent(botoneliminararticulos))
                .addGap(179, 179, 179))
        );

        TabbClientes.addTab("articulos", jPanel2);

        jPanel4.setBackground(new java.awt.Color(206, 219, 227));
        jPanel4.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jPanel4AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jLabel7.setText("NumeroFactura");

        jLabel8.setText("Codigo");

        jLabel9.setText("Cantidad");

        jLabel10.setText("ValorUnitario");

        jLabel11.setText("ValorTotal");

        botondetalleinsertar.setText("Insertar");
        botondetalleinsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botondetalleinsertarActionPerformed(evt);
            }
        });

        botondetallemodificar.setText("Modificar");
        botondetallemodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botondetallemodificarActionPerformed(evt);
            }
        });

        botondetalleEliminar.setText("Eliminar");
        botondetalleEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botondetalleEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(botondetalleinsertar)
                .addGap(18, 18, 18)
                .addComponent(botondetallemodificar)
                .addGap(18, 18, 18)
                .addComponent(botondetalleEliminar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 199, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(txtdetalleNumeroFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtdetalleCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtdetalleCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtdetalleValorUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtdetalleValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtdetalleCantidad, txtdetalleCodigo, txtdetalleNumeroFactura, txtdetalleValorTotal, txtdetalleValorUnitario});

        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtdetalleNumeroFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtdetalleCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtdetalleCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtdetalleValorUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtdetalleValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(53, 53, 53)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botondetalleinsertar)
                    .addComponent(botondetallemodificar)
                    .addComponent(botondetalleEliminar))
                .addGap(270, 270, 270))
        );

        TabbClientes.addTab("Factura detalle", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TabbClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(TabbClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombreActionPerformed
        
    }//GEN-LAST:event_txtnombreActionPerformed

    private void txtCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoActionPerformed
        
    }//GEN-LAST:event_txtCorreoActionPerformed

    private void botonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonModificarActionPerformed
    Conexion cc= new Conexion();
        Connection cn=cc.estableceConexion();
        String cod,nom,ape,direc,Correo,ciudad;
        String sql;
        cod=txtidentificacion.getText();
        nom=txtnombre.getText();
        ape=txtApellido.getText();
        direc=txtDireccion.getText();
        Correo=txtCorreo.getText();
        ciudad=txtCiudad.getText();
        sql="update tblclientes set nombre=?, apellido=? where codigo="+cod;
        try{
            PreparedStatement pst = cn.prepareStatement(sql);
            pst.setString(1,nom);
            pst.setString(2,ape);
            pst.setString(3,direc);
            pst.setString(4,Correo);
            pst.setString(5,ciudad);
            int registro=pst.executeUpdate();
            if (registro>0){
                JOptionPane.showMessageDialog(null, "El registro se actualizo correctamente");
             }
        }catch (Exception e)
        {
             JOptionPane.showMessageDialog(null, "El registro  no se actualizo");
        }         
    }//GEN-LAST:event_botonModificarActionPerformed

    private void txtAcodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAcodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAcodigoActionPerformed

    private void txtAciudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAciudadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAciudadActionPerformed

    private void jPanel4AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jPanel4AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel4AncestorAdded

    private void botonInsetarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonInsetarActionPerformed
        // TODO add your handling code here:
        Conexion cc= new Conexion();
        Connection cn=cc.estableceConexion();
        String cod,nom,ape,direccion,correo,ciudad;
        String sql="";
        cod=txtidentificacion.getText();
        nom=txtnombre.getText();
        ape=txtApellido.getText();
        direccion=txtDireccion.getText();
        correo=txtCorreo.getText();
        ciudad=txtCiudad.getText();
        
        sql="insert into tblclientes (codigo,nombre,apellido) values (?,?,?)";
        try{
            PreparedStatement pst=cn.prepareStatement(sql);
            pst.setString(1,cod);
            pst.setString(2,nom);
            pst.setString(3,direccion);
            pst.setString(4,correo);
            pst.setString(5,ciudad);
            pst.setString(6,ape);
            
            int registro=pst.executeUpdate();
            if (registro>0)
            {
               JOptionPane.showMessageDialog(null,"Registro almacenado correctamente");
              // limpiar();
            }
        }catch(Exception e){
               JOptionPane.showMessageDialog(null,"Registro no almacenado");
               }
    }//GEN-LAST:event_botonInsetarActionPerformed

    private void botonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarActionPerformed
        // TODO add your handling code here:
        Conexion cc= new Conexion();
        Connection cn=cc.estableceConexion();
        String cod;
        String sql;
        cod=txtidentificacion.getText();
        sql="delete from tblclientes where codigo="+cod;
        JOptionPane.showMessageDialog(null,sql);
        try{
           PreparedStatement pst = cn.prepareStatement(sql);
           int registro=pst.executeUpdate();
           if (registro>0){
               JOptionPane.showMessageDialog(null,"El registro se elimino correctamente");
               }
            }catch (Exception e)
                        {
                        JOptionPane.showMessageDialog(null,"El registro no se elimino");
                        }
    }//GEN-LAST:event_botonEliminarActionPerformed

    private void botonfacturaInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonfacturaInsertarActionPerformed
        // TODO add your handling code here:
         Conexion cc= new Conexion();
        Connection cn=cc.estableceConexion();
        String nombrefactura,facturaidentificacion,facturafecha;
        String sql="";
        nombrefactura=txtfacturanumerofactura.getText();
        facturaidentificacion=txtfacturaidentificacion.getText();
        facturafecha=txtfacturafecha.getText();
        sql="insert into tblclientes (codigo,nombre,apellido) values (?,?,?)";
        try{
            PreparedStatement pst=cn.prepareStatement(sql);
            pst.setString(1,nombrefactura);
            pst.setString(2,facturaidentificacion);
            pst.setString(3,facturafecha);
            int registro=pst.executeUpdate();
            if (registro>0)
            {
               JOptionPane.showMessageDialog(null,"Registro almacenado correctamente");
              // limpiar();
            }
        }catch(Exception e){
               JOptionPane.showMessageDialog(null,"Registro no almacenado");
               }
    }//GEN-LAST:event_botonfacturaInsertarActionPerformed

    private void botonfacturamodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonfacturamodificarActionPerformed
        // TODO add your handling code here:
        Conexion cc= new Conexion();
        Connection cn=cc.estableceConexion();
        String nombrefactura,facturaidentificacion,facturafecha;
        String sql;
        nombrefactura=txtfacturanumerofactura.getText();
        facturaidentificacion=txtfacturaidentificacion.getText();
        facturafecha=txtfacturafecha.getText();
        sql="update tblclientes set nombre=?, apellido=? where codigo="+nombrefactura;
        try{
            PreparedStatement pst = cn.prepareStatement(sql);
            pst.setString(1,nombrefactura);
            pst.setString(2,facturaidentificacion);
            pst.setString(3,facturafecha);
            int registro=pst.executeUpdate();
            if (registro>0){
                JOptionPane.showMessageDialog(null, "El registro se actualizo correctamente");
             }
        }catch (Exception e)
        {
             JOptionPane.showMessageDialog(null, "El registro  no se actualizo");
        }
    }//GEN-LAST:event_botonfacturamodificarActionPerformed

    private void botonfacturaeliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonfacturaeliminarActionPerformed
        // TODO add your handling code here:
        Conexion cc= new Conexion();
        Connection cn=cc.estableceConexion();
        String nombrefactura;
        String sql;
        nombrefactura=txtfacturanumerofactura.getText();
        sql="delete from tblclientes where codigo="+nombrefactura;
        JOptionPane.showMessageDialog(null,sql);
        try{
           PreparedStatement pst = cn.prepareStatement(sql);
           int registro=pst.executeUpdate();
           if (registro>0){
               JOptionPane.showMessageDialog(null,"El registro se elimino correctamente");
               }
            }catch (Exception e)
                        {
                        JOptionPane.showMessageDialog(null,"El registro no se elimino");
                        }
    }//GEN-LAST:event_botonfacturaeliminarActionPerformed

    private void botonarticulosInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonarticulosInsertarActionPerformed
        // TODO add your handling code here:
        
        
        
    }//GEN-LAST:event_botonarticulosInsertarActionPerformed

    private void botondetalleinsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botondetalleinsertarActionPerformed
        // TODO add your handling code here:
        Conexion cc= new Conexion();
        Connection cn=cc.estableceConexion();
        String detalleNumeroFactura,detalleCodigo,detalleValorUnitario,detalleValorTotal;
        String sql="";
        detalleNumeroFactura=txtdetalleNumeroFactura.getText();
        detalleCodigo=txtdetalleCodigo.getText();
        detalleValorUnitario=txtdetalleValorUnitario.getText();
        detalleValorTotal=txtdetalleValorTotal.getText();
        sql="insert into tblclientes (codigo,nombre,apellido) values (?,?,?)";
        try{
            PreparedStatement pst=cn.prepareStatement(sql);
            pst.setString(1,detalleNumeroFactura);
            pst.setString(2,detalleCodigo);
            pst.setString(3,detalleValorUnitario);
            pst.setString(4,detalleValorTotal);
            int registro=pst.executeUpdate();
            if (registro>0)
            {
               JOptionPane.showMessageDialog(null,"Registro almacenado correctamente");
              // limpiar();
            }
        }catch(Exception e){
               JOptionPane.showMessageDialog(null,"Registro no almacenado");
               }
    }//GEN-LAST:event_botondetalleinsertarActionPerformed

    private void botondetallemodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botondetallemodificarActionPerformed
        // TODO add your handling code here:
        Conexion cc= new Conexion();
        Connection cn=cc.estableceConexion();
        String detalleNumeroFactura,detalleCodigo,detalleValorUnitario,detalleValorTotal;
        String sql;
        detalleNumeroFactura=txtdetalleNumeroFactura.getText();
        detalleCodigo=txtdetalleCodigo.getText();
        detalleValorUnitario=txtdetalleValorUnitario.getText();
        detalleValorTotal=txtdetalleValorTotal.getText();
        sql="update tblclientes set nombre=?, apellido=? where codigo="+detalleCodigo;
        try{
            PreparedStatement pst = cn.prepareStatement(sql);
            pst.setString(1,detalleNumeroFactura);
            pst.setString(2,detalleCodigo);
            pst.setString(3,detalleValorUnitario);
            pst.setString(4,detalleValorTotal);
            int registro=pst.executeUpdate();
            if (registro>0){
                JOptionPane.showMessageDialog(null, "El registro se actualizo correctamente");
             }
        }catch (Exception e)
        {
             JOptionPane.showMessageDialog(null, "El registro  no se actualizo");
        } 
    }//GEN-LAST:event_botondetallemodificarActionPerformed

    private void botondetalleEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botondetalleEliminarActionPerformed
        // TODO add your handling code here:
        Conexion cc= new Conexion();
        Connection cn=cc.estableceConexion();
        String detalleCodigo;
        String sql;
        detalleCodigo=txtdetalleCodigo.getText();
        sql="delete from tblclientes where codigo="+detalleCodigo;
        JOptionPane.showMessageDialog(null,sql);
        try{
           PreparedStatement pst = cn.prepareStatement(sql);
           int registro=pst.executeUpdate();
           if (registro>0){
               JOptionPane.showMessageDialog(null,"El registro se elimino correctamente");
               }
            }catch (Exception e)
                        {
                        JOptionPane.showMessageDialog(null,"El registro no se elimino");
                        }
    }//GEN-LAST:event_botondetalleEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane TabbClientes;
    private javax.swing.JButton botonEliminar;
    private javax.swing.JButton botonInsetar;
    private javax.swing.JButton botonModificar;
    private javax.swing.JButton botonarticulosInsertar;
    private javax.swing.JButton botonarticulosmodificar;
    private javax.swing.JButton botondetalleEliminar;
    private javax.swing.JButton botondetalleinsertar;
    private javax.swing.JButton botondetallemodificar;
    private javax.swing.JButton botoneliminararticulos;
    private javax.swing.JButton botonfacturaInsertar;
    private javax.swing.JButton botonfacturaeliminar;
    private javax.swing.JButton botonfacturamodificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblApellido;
    private javax.swing.JLabel lblCiudad;
    private javax.swing.JLabel lblCorrero;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblIdentificacion;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNumerofactura;
    private javax.swing.JLabel lblfacturaIdentificacion;
    private javax.swing.JLabel lblfacturafecha;
    private javax.swing.JTextField txtAciudad;
    private javax.swing.JTextField txtAcodigo;
    private javax.swing.JTextField txtAdescripcion;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtApreciounitario;
    private javax.swing.JTextField txtApreveedor;
    private javax.swing.JTextField txtAunidaddemedida;
    private javax.swing.JTextField txtCiudad;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtdetalleCantidad;
    private javax.swing.JTextField txtdetalleCodigo;
    private javax.swing.JTextField txtdetalleNumeroFactura;
    private javax.swing.JTextField txtdetalleValorTotal;
    private javax.swing.JTextField txtdetalleValorUnitario;
    private javax.swing.JTextField txtfacturafecha;
    private javax.swing.JTextField txtfacturaidentificacion;
    private javax.swing.JTextField txtfacturanumerofactura;
    private javax.swing.JTextField txtidentificacion;
    private javax.swing.JTextField txtnombre;
    // End of variables declaration//GEN-END:variables
}
